### ISSUE TITLE
Configure miq_bot

### ISSUE THREAD

**Issue by miha-plesko** [ManageIQ/manageiq-providers-azure_stack#13]
Not sure where is this supposed to be configured, but currently the

```
@miq_bot COMMAND
```

doesn't seem to work.

**Comment by miha-plesko** [comment]
CC-ing @mancabizjak as she noticed it. She has no permissions on this repo but would like to be able to assign and label PRs as well :)

**Comment by agrare** [comment]
@bdunne can you add this repo to the bot?

**Comment by bdunne** [comment]
It is listed as one of the core repos in the bot config, but it sounds like the bot is not getting notifications for it.  @Fryguy can you check on that?

**Comment by miha-plesko** [comment]
It seems to work now, thanks
